-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd("highlight clear") end
vim.g.colors_name = "snapshot"

-- Highlight groups
local hi = vim.api.nvim_set_hl

if vim.o.background == "dark" then
  hi(0, "@annotation", { fg = "#dfab25" })
  hi(0, "@attribute", { fg = "#dfab25" })
  hi(0, "@attribute.builtin", { link = "@attribute" })
  hi(0, "@character.special", { link = "SpecialChar" })
  hi(0, "@class", { fg = "#5eb7ff" })
  hi(0, "@comment.documentation", { link = "@comment" })
  hi(0, "@comment.error", { bg = "#f8747e", fg = "#1a1d23" })
  hi(0, "@comment.hint", { bg = "#50a4e9", fg = "#1a1d23" })
  hi(0, "@comment.info", { bg = "#00b298", fg = "#1a1d23" })
  hi(0, "@comment.todo", { bg = "#d09214", fg = "#1a1d23" })
  hi(0, "@comment.warning", { bg = "#eb8332", fg = "#1a1d23" })
  hi(0, "@conditional", { link = "@keyword.conditional" })
  hi(0, "@conditional.ternary", { link = "@keyword.conditional.ternary" })
  hi(0, "@constant.builtin", { link = "@constant" })
  hi(0, "@constant.macro", { link = "@constant" })
  hi(0, "@constant.rust", { fg = "#4ac2b8" })
  hi(0, "@constructor", { link = "@function" })
  hi(0, "@constructor.lua", { fg = "#f5983a" })
  hi(0, "@constructor.tsx", { fg = "#dd97f1" })
  hi(0, "@constructor.typescript", { fg = "#dd97f1" })
  hi(0, "@debug", { link = "@keyword.debug" })
  hi(0, "@decorator", { fg = "#f5983a" })
  hi(0, "@define", { link = "@keyword.directive.define" })
  hi(0, "@diff.delta", { link = "DiffChange" })
  hi(0, "@diff.minus", { link = "DiffDelete" })
  hi(0, "@diff.plus", { link = "DiffAdded" })
  hi(0, "@enum", { fg = "#4ac2b8" })
  hi(0, "@enumMember", { fg = "#f5983a" })
  hi(0, "@error", { link = "Error" })
  hi(0, "@event", { fg = "#f5983a" })
  hi(0, "@exception", { link = "@keyword.exception" })
  hi(0, "@field", { link = "@variable.member" })
  hi(0, "@field.yaml", { fg = "#ff838b" })
  hi(0, "@float", { link = "@number.float" })
  hi(0, "@function.builtin", { fg = "#4ac2b8" })
  hi(0, "@function.call", { link = "@function" })
  hi(0, "@function.macro", { fg = "#dfab25" })
  hi(0, "@function.macro.rust", { fg = "#ff838b" })
  hi(0, "@function.method", { link = "@function" })
  hi(0, "@function.method.call", { link = "@function.method" })
  hi(0, "@function.method.call.php", { link = "Function" })
  hi(0, "@function.method.php", { link = "Function" })
  hi(0, "@ibl.indent.char.1", { fg = "#3a3e47", nocombine = true })
  hi(0, "@ibl.scope.char.1", { fg = "#9b9fa9", nocombine = true })
  hi(0, "@ibl.scope.underline.1", { sp = "#9b9fa9", underline = true })
  hi(0, "@ibl.whitespace.char.1", { fg = "#3a3e47", nocombine = true })
  hi(0, "@include", { link = "@keyword.include" })
  hi(0, "@interface", { fg = "#f5983a" })
  hi(0, "@keyword.conditional", { link = "Conditional" })
  hi(0, "@keyword.conditional.ternary", { link = "@keyword.conditional" })
  hi(0, "@keyword.corotine", { link = "Keyword" })
  hi(0, "@keyword.debug", { link = "Debug" })
  hi(0, "@keyword.directive", { link = "Keyword" })
  hi(0, "@keyword.directive.define", { link = "Keyword" })
  hi(0, "@keyword.exception", { link = "Exception" })
  hi(0, "@keyword.export", { link = "@keyword" })
  hi(0, "@keyword.function", { link = "Keyword" })
  hi(0, "@keyword.import", { link = "Include" })
  hi(0, "@keyword.modifier", { link = "Structure" })
  hi(0, "@keyword.operator", { link = "Keyword" })
  hi(0, "@keyword.repeat", { link = "Repeat" })
  hi(0, "@keyword.return", { link = "Keyword" })
  hi(0, "@keyword.storage", { link = "StorageClass" })
  hi(0, "@keyword.type", { link = "Typedef" })
  hi(0, "@label.json", { fg = "#5eb7ff" })
  hi(0, "@literal.markdown", { fg = "#87c05f" })
  hi(0, "@lsp.type.boolean", { link = "@boolean" })
  hi(0, "@lsp.type.builtinType", { link = "@type.builtin" })
  hi(0, "@lsp.type.comment", { link = "@comment" })
  hi(0, "@lsp.type.enum", { link = "@type" })
  hi(0, "@lsp.type.enumMember", { link = "@constant" })
  hi(0, "@lsp.type.escapeSequence", { link = "@string.escape" })
  hi(0, "@lsp.type.formatSpecifier", { link = "@punctuation.special" })
  hi(0, "@lsp.type.function.rust", { fg = "#adb0bb" })
  hi(0, "@lsp.type.interface", { link = "@interface" })
  hi(0, "@lsp.type.keyword", { link = "@keyword" })
  hi(0, "@lsp.type.macro.rust", { link = "@function.macro.rust" })
  hi(0, "@lsp.type.namespace", { link = "@namespace" })
  hi(0, "@lsp.type.namespace.rust", { link = "@namespace.rust" })
  hi(0, "@lsp.type.number", { link = "@number" })
  hi(0, "@lsp.type.operator", { link = "@operator" })
  hi(0, "@lsp.type.parameter", { link = "@parameter" })
  hi(0, "@lsp.type.property", { link = "@property" })
  hi(0, "@lsp.type.selfKeyword", { link = "@variable.builtin" })
  hi(0, "@lsp.type.typeAlias", { link = "@type.definition" })
  hi(0, "@lsp.type.unresolvedReference", { link = "@error" })
  hi(0, "@lsp.type.variable", { link = "@variable" })
  hi(0, "@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
  hi(0, "@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
  hi(0, "@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
  hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
  hi(0, "@lsp.typemod.function.defaultLibrary.rust", { fg = "#adb0bb" })
  hi(0, "@lsp.typemod.function.global", { link = "@function.builtin" })
  hi(0, "@lsp.typemod.keyword.async", { link = "@keyword.coroutine" })
  hi(0, "@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
  hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
  hi(0, "@lsp.typemod.method.reference", { link = "@function" })
  hi(0, "@lsp.typemod.method.trait", { link = "@function" })
  hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
  hi(0, "@lsp.typemod.selfKeyword.defaultLibrary", { link = "@keyword" })
  hi(0, "@lsp.typemod.string.injected", { link = "@string" })
  hi(0, "@lsp.typemod.type.defaultLibrary", { link = "@type.builtin" })
  hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
  hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
  hi(0, "@lsp.typemod.variable.readonly", { link = "@constant" })
  hi(0, "@markup.environment", { fg = "#f5983a" })
  hi(0, "@markup.heading", { bold = true, fg = "#adb0bb" })
  hi(0, "@markup.heading.1.markdown", { bold = true, fg = "#dd97f1" })
  hi(0, "@markup.heading.2.markdown", { bold = true, fg = "#5eb7ff" })
  hi(0, "@markup.heading.3.markdown", { bold = true, fg = "#4ac2b8" })
  hi(0, "@markup.heading.4.markdown", { bold = true, fg = "#87c05f" })
  hi(0, "@markup.heading.5.markdown", { bold = true, fg = "#dfab25" })
  hi(0, "@markup.italic", { fg = "#adb0bb", italic = true })
  hi(0, "@markup.link", { bold = true, fg = "#dfab25" })
  hi(0, "@markup.link.label", { link = "String" })
  hi(0, "@markup.link.url", { fg = "#5eb7ff", italic = true, underline = true })
  hi(0, "@markup.list", { link = "Special" })
  hi(0, "@markup.list.checked", { bg = "#75ad47", fg = "#1a1d23" })
  hi(0, "@markup.list.unchecked", { bg = "#cc83e3", fg = "#1a1d23" })
  hi(0, "@markup.math", { fg = "#5eb7ff" })
  hi(0, "@markup.quote", { fg = "#adb0bb", italic = true })
  hi(0, "@markup.raw", { fg = "#ff838b" })
  hi(0, "@markup.raw.block", { fg = "#adb0bb" })
  hi(0, "@markup.strikethrough", { fg = "#adb0bb", strikethrough = true })
  hi(0, "@markup.strong", { bold = true, fg = "#adb0bb" })
  hi(0, "@markup.underline", { link = "Underline" })
  hi(0, "@method", { link = "@function" })
  hi(0, "@method.call", { link = "@function.method" })
  hi(0, "@method.call.php", { link = "@function.method.call.php" })
  hi(0, "@method.php", { link = "@function.method.php" })
  hi(0, "@modifier", { fg = "#f5983a" })
  hi(0, "@module", { link = "Keyword" })
  hi(0, "@module.builtin", { fg = "#dfab25" })
  hi(0, "@module.rust", { fg = "#dd97f1" })
  hi(0, "@namespace", { link = "@module" })
  hi(0, "@namespace.builtin", { link = "@module.builtin" })
  hi(0, "@namespace.rust", { link = "@module.rust" })
  hi(0, "@none.markdown", { fg = "#adb0bb" })
  hi(0, "@number.css", { fg = "#4ac2b8" })
  hi(0, "@number.float", { link = "Float" })
  hi(0, "@parameter", { link = "@variable.parameter" })
  hi(0, "@preproc", { link = "@keyword.directive" })
  hi(0, "@property", { fg = "#ff838b" })
  hi(0, "@property.class.css", { fg = "#dfab25" })
  hi(0, "@property.cpp", { fg = "#f5983a" })
  hi(0, "@property.css", { fg = "#f5983a" })
  hi(0, "@property.id.css", { fg = "#5eb7ff" })
  hi(0, "@property.toml", { fg = "#ff838b" })
  hi(0, "@punctuation.bracket", { fg = "#adb0bb" })
  hi(0, "@punctuation.delimiter", { fg = "#adb0bb" })
  hi(0, "@punctuation.delimiter.markdown", { link = "@punctuation.delimiter" })
  hi(0, "@punctuation.special", { fg = "#adb0bb" })
  hi(0, "@punctuation.special.markdown", { link = "@punctuation.special" })
  hi(0, "@punctuation.special.rust", { fg = "#dd97f1" })
  hi(0, "@regexp", { fg = "#4ac2b8" })
  hi(0, "@repeat", { link = "@keyword.repeat" })
  hi(0, "@storageclass", { link = "@keyword.storageclass" })
  hi(0, "@string.documentation", { link = "String" })
  hi(0, "@string.escape", { fg = "#ff838b" })
  hi(0, "@string.plain.css", { fg = "#87c05f" })
  hi(0, "@string.regex", { link = "@string.regexp" })
  hi(0, "@string.regexp", { link = "String" })
  hi(0, "@string.special", { link = "String" })
  hi(0, "@string.special.path", { link = "String" })
  hi(0, "@string.special.symbol", { link = "String" })
  hi(0, "@string.special.symbol.ruby", { fg = "#f5983a" })
  hi(0, "@string.special.url", { link = "@markup.link.url" })
  hi(0, "@struct", { fg = "#5eb7ff" })
  hi(0, "@symbol", { link = "@string.special.symbol" })
  hi(0, "@symbol.ruby", { link = "@string.special.symbol.ruby" })
  hi(0, "@tag", { fg = "#ff838b" })
  hi(0, "@tag.attribute", { fg = "#4ac2b8" })
  hi(0, "@tag.attribute.tsx", { fg = "#dd97f1", italic = true })
  hi(0, "@tag.delimiter", { fg = "#adb0bb" })
  hi(0, "@text", { fg = "#adb0bb" })
  hi(0, "@text.checked", { link = "@markup.list.checked" })
  hi(0, "@text.danger", { link = "@comment.error" })
  hi(0, "@text.diff.add", { link = "@diff.plus" })
  hi(0, "@text.diff.delete", { link = "@diff.minus" })
  hi(0, "@text.emphasis", { link = "@markup.emphasis" })
  hi(0, "@text.environment", { link = "@markup.environment" })
  hi(0, "@text.environment.name", { link = "@markup.environment" })
  hi(0, "@text.literal", { link = "@markup.raw" })
  hi(0, "@text.math", { link = "@markup.math" })
  hi(0, "@text.note", { link = "@comment.hint" })
  hi(0, "@text.quote", { link = "@markup.quote" })
  hi(0, "@text.reference", { link = "@markup.link" })
  hi(0, "@text.strike", { link = "@markup.strikethrough" })
  hi(0, "@text.strong", { link = "@markup.strong" })
  hi(0, "@text.title", { link = "@markup.heading" })
  hi(0, "@text.title.1.markdown", { link = "@markup.heading.1.markdown" })
  hi(0, "@text.title.2.markdown", { link = "@markup.heading.2.markdown" })
  hi(0, "@text.title.3.markdown", { link = "@markup.heading.3.markdown" })
  hi(0, "@text.title.4.markdown", { link = "@markup.heading.4.markdown" })
  hi(0, "@text.title.5.markdown", { link = "@markup.heading.5.markdown" })
  hi(0, "@text.todo", { link = "@comment.todo" })
  hi(0, "@text.todo.checked", { link = "@text.checked" })
  hi(0, "@text.todo.danger", { link = "@text.danger" })
  hi(0, "@text.todo.note", { link = "@text.note" })
  hi(0, "@text.todo.unchecked", { link = "@text.unchecked" })
  hi(0, "@text.todo.warning", { link = "@text.warning" })
  hi(0, "@text.unchecked", { link = "@markup.list.unchecked" })
  hi(0, "@text.underline", { link = "@markup.underline" })
  hi(0, "@text.uri", { link = "@markup.link.url" })
  hi(0, "@text.warning", { link = "@comment.warning" })
  hi(0, "@title.markdown", { link = "markup.heading" })
  hi(0, "@type.builtin", { fg = "#dfab25" })
  hi(0, "@type.css", { fg = "#f5983a" })
  hi(0, "@type.definition", { link = "@type" })
  hi(0, "@type.qualifier", { link = "@type" })
  hi(0, "@type.qualifier.php", { link = "Keyword" })
  hi(0, "@type.qualifier.typescript", { link = "Keyword" })
  hi(0, "@type.rust", { fg = "#4ac2b8" })
  hi(0, "@type.tag.css", { fg = "#dd97f1" })
  hi(0, "@typeParameter", { fg = "#dfab25" })
  hi(0, "@variable", { link = "Identifier" })
  hi(0, "@variable.builtin", { fg = "#4ac2b8" })
  hi(0, "@variable.lua", { link = "@variable" })
  hi(0, "@variable.member", { link = "@property" })
  hi(0, "@variable.parameter", { fg = "#f5983a" })
  hi(0, "@variable.parameter.builtin", { link = "@variable.parameter" })
  hi(0, "AerialArrayIcon", { link = "@constant" })
  hi(0, "AerialBooleanIcon", { link = "@boolean" })
  hi(0, "AerialClassIcon", { link = "@type" })
  hi(0, "AerialConstantIcon", { link = "@constant" })
  hi(0, "AerialConstructorIcon", { link = "@constructor" })
  hi(0, "AerialEnumIcon", { link = "@type" })
  hi(0, "AerialEnumMemberIcon", { link = "@field" })
  hi(0, "AerialEventIcon", { link = "@type" })
  hi(0, "AerialFieldIcon", { link = "@field" })
  hi(0, "AerialFileIcon", { link = "@text.uri" })
  hi(0, "AerialFunctionIcon", { link = "@function" })
  hi(0, "AerialGuide", { fg = "#3a3e47" })
  hi(0, "AerialInterfaceIcon", { link = "@type" })
  hi(0, "AerialKeyIcon", { link = "@type" })
  hi(0, "AerialLine", { fg = "#50a4e9" })
  hi(0, "AerialMethodIcon", { link = "@method" })
  hi(0, "AerialModuleIcon", { link = "@namespace" })
  hi(0, "AerialNamespaceIcon", { link = "@namespace" })
  hi(0, "AerialNormal", { fg = "#9b9fa9" })
  hi(0, "AerialNullIcon", { link = "@type" })
  hi(0, "AerialNumberIcon", { link = "@number" })
  hi(0, "AerialObjectIcon", { link = "@type" })
  hi(0, "AerialOperatorIcon", { link = "@operator" })
  hi(0, "AerialPackageIcon", { link = "@namespace" })
  hi(0, "AerialPropertyIcon", { link = "@property" })
  hi(0, "AerialStringIcon", { link = "@string" })
  hi(0, "AerialStructIcon", { link = "@type" })
  hi(0, "AerialTypeIcon", { link = "@type" })
  hi(0, "AerialTypeParameterIcon", { link = "@parameter" })
  hi(0, "AerialVariableIcon", { link = "@variable" })
  hi(0, "Bold", { bold = true })
  hi(0, "Boolean", { fg = "#f5983a" })
  hi(0, "Character", { fg = "#87c05f" })
  hi(0, "CmpItemAbbr", { fg = "#9b9fa9" })
  hi(0, "CmpItemAbbrDefault", { fg = "#9b9fa9" })
  hi(0, "CmpItemAbbrDeprecated", { fg = "#ff838b", strikethrough = true })
  hi(0, "CmpItemAbbrDeprecatedDefault", { fg = "#696c76" })
  hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#e0e0ee" })
  hi(0, "CmpItemAbbrMatchDefault", { fg = "#9b9fa9" })
  hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#e0e0ee" })
  hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = "#9b9fa9" })
  hi(0, "CmpItemKimdStruct", { link = "@type" })
  hi(0, "CmpItemKind", { fg = "#dfab25" })
  hi(0, "CmpItemKindArray", { bg = "#eb8332", fg = "#14161b" })
  hi(0, "CmpItemKindBoolean", { bg = "#eb8332", fg = "#14161b" })
  hi(0, "CmpItemKindClass", { bg = "#cc83e3", fg = "#14161b" })
  hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
  hi(0, "CmpItemKindColor", { bg = "#f8747e", fg = "#14161b" })
  hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
  hi(0, "CmpItemKindConstant", { bg = "#eb8332", fg = "#14161b" })
  hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
  hi(0, "CmpItemKindConstructor", { bg = "#73c7ff", fg = "#14161b" })
  hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
  hi(0, "CmpItemKindDefault", { fg = "#5eb7ff" })
  hi(0, "CmpItemKindEnum", { bg = "#cc83e3", fg = "#14161b" })
  hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
  hi(0, "CmpItemKindEnumMember", { bg = "#d09214", fg = "#14161b" })
  hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
  hi(0, "CmpItemKindEvent", { bg = "#f8747e", fg = "#14161b" })
  hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
  hi(0, "CmpItemKindField", { bg = "#d09214", fg = "#14161b" })
  hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
  hi(0, "CmpItemKindFile", { bg = "#50a4e9", fg = "#14161b" })
  hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
  hi(0, "CmpItemKindFolder", { bg = "#50a4e9", fg = "#14161b" })
  hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
  hi(0, "CmpItemKindFunction", { bg = "#73c7ff", fg = "#14161b" })
  hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
  hi(0, "CmpItemKindInterface", { bg = "#cc83e3", fg = "#14161b" })
  hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
  hi(0, "CmpItemKindKey", { bg = "#d09214", fg = "#14161b" })
  hi(0, "CmpItemKindKeyword", { bg = "#00b298", fg = "#14161b" })
  hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
  hi(0, "CmpItemKindMethod", { bg = "#73c7ff", fg = "#14161b" })
  hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
  hi(0, "CmpItemKindModule", { bg = "#cc83e3", fg = "#14161b" })
  hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
  hi(0, "CmpItemKindNamespace", { bg = "#f8747e", fg = "#14161b" })
  hi(0, "CmpItemKindNull", { bg = "#9b9fa9", fg = "#14161b" })
  hi(0, "CmpItemKindNumber", { bg = "#eb8332", fg = "#14161b" })
  hi(0, "CmpItemKindObject", { bg = "#9b9fa9", fg = "#14161b" })
  hi(0, "CmpItemKindOperator", { bg = "#00b298", fg = "#14161b" })
  hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
  hi(0, "CmpItemKindPackage", { bg = "#cc83e3", fg = "#14161b" })
  hi(0, "CmpItemKindProperty", { bg = "#d09214", fg = "#14161b" })
  hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
  hi(0, "CmpItemKindReference", { bg = "#00b298", fg = "#14161b" })
  hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
  hi(0, "CmpItemKindSnippet", { bg = "#75ad47", fg = "#14161b" })
  hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
  hi(0, "CmpItemKindString", { bg = "#75ad47", fg = "#14161b" })
  hi(0, "CmpItemKindStruct", { bg = "#cc83e3", fg = "#14161b" })
  hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
  hi(0, "CmpItemKindText", { bg = "#75ad47", fg = "#14161b" })
  hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
  hi(0, "CmpItemKindTypeParameter", { bg = "#00b298", fg = "#14161b" })
  hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
  hi(0, "CmpItemKindUnit", { bg = "#00b298", fg = "#14161b" })
  hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
  hi(0, "CmpItemKindValue", { bg = "#50a4e9", fg = "#14161b" })
  hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
  hi(0, "CmpItemKindVariable", { bg = "#00b298", fg = "#14161b" })
  hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
  hi(0, "CmpItemMenuDefault", { fg = "#9b9fa9" })
  hi(0, "ColorColumn", { bg = "#1e222a" })
  hi(0, "Comment", { fg = "#696c76", italic = true })
  hi(0, "Conceal", { fg = "#494d56" })
  hi(0, "Conditional", { fg = "#dd97f1" })
  hi(0, "Constant", { fg = "#dfab25" })
  hi(0, "CurSearch", { link = "IncSearch" })
  hi(0, "Cursor", { bg = "#9b9fa9", fg = "#1a1d23" })
  hi(0, "CursorColumn", { bg = "#1e222a" })
  hi(0, "CursorLine", { bg = "#1e222a" })
  hi(0, "CursorLineNr", { fg = "#adb0bb" })
  hi(0, "DashboardCenter", { fg = "#5eb7ff" })
  hi(0, "DashboardFooter", { fg = "#4ac2b8" })
  hi(0, "DashboardHeader", { fg = "#4ac2b8" })
  hi(0, "DashboardShortcut", { fg = "#dfab25" })
  hi(0, "Debug", { fg = "#50a4e9" })
  hi(0, "Define", { fg = "#dd97f1" })
  hi(0, "Delimiter", { fg = "#5eb7ff" })
  hi(0, "DiagnosticError", { fg = "#f8747e" })
  hi(0, "DiagnosticHint", { fg = "#00b298" })
  hi(0, "DiagnosticInfo", { fg = "#50a4e9" })
  hi(0, "DiagnosticOk", { fg = "#75ad47" })
  hi(0, "DiagnosticUnderlineError", { sp = "#f8747e", undercurl = true })
  hi(0, "DiagnosticUnderlineHint", { sp = "#00b298", undercurl = true })
  hi(0, "DiagnosticUnderlineInfo", { sp = "#50a4e9", undercurl = true })
  hi(0, "DiagnosticUnderlineOk", { sp = "#75ad47", undercurl = true })
  hi(0, "DiagnosticUnderlineWarn", { sp = "#d09214", undercurl = true })
  hi(0, "DiagnosticWarn", { fg = "#d09214" })
  hi(0, "DiffAdd", { bg = "#354632" })
  hi(0, "DiffAdded", { fg = "#87c05f" })
  hi(0, "DiffChange", { bg = "#4b4124" })
  hi(0, "DiffChanged", { fg = "#5eb7ff" })
  hi(0, "DiffDelete", { bg = "#53373d" })
  hi(0, "DiffFile", { fg = "#5eb7ff" })
  hi(0, "DiffIndexLine", { fg = "#4ac2b8" })
  hi(0, "DiffLine", { fg = "#adb0bb" })
  hi(0, "DiffNewFile", { fg = "#87c05f" })
  hi(0, "DiffOldFile", { fg = "#f5983a" })
  hi(0, "DiffRemoved", { fg = "#ff838b" })
  hi(0, "DiffText", { bg = "#554824" })
  hi(0, "Directory", { fg = "#50a4e9" })
  hi(0, "EndOfBuffer", { fg = "#3a3e47" })
  hi(0, "Error", { fg = "#f8747e" })
  hi(0, "ErrorMsg", { fg = "#ff838b" })
  hi(0, "Exception", { fg = "#dd97f1" })
  hi(0, "Float", { fg = "#dfab25" })
  hi(0, "FloatBorder", { bg = "#14161b", fg = "#3a3e47" })
  hi(0, "FloatTitle", { bg = "#14161b", bold = true, fg = "#50a4e9" })
  hi(0, "FoldColumn", { fg = "#3a3e47" })
  hi(0, "Folded", { fg = "#3a3e47" })
  hi(0, "Function", { fg = "#5eb7ff" })
  hi(0, "GitSignsAdd", { fg = "#75ad47" })
  hi(0, "GitSignsChange", { fg = "#eb8332" })
  hi(0, "GitSignsDelete", { fg = "#f8747e" })
  hi(0, "GitSignsStagedAdd", { fg = "#3a5623" })
  hi(0, "GitSignsStagedAddCul", { fg = "#3a5623" })
  hi(0, "GitSignsStagedAddLn", { bg = "#354632" })
  hi(0, "GitSignsStagedAddNr", { fg = "#3a5623" })
  hi(0, "GitSignsStagedChange", { fg = "#754119" })
  hi(0, "GitSignsStagedChangeCul", { fg = "#754119" })
  hi(0, "GitSignsStagedChangeLn", { bg = "#4b4124" })
  hi(0, "GitSignsStagedChangeNr", { fg = "#754119" })
  hi(0, "GitSignsStagedChangedelete", { fg = "#754119" })
  hi(0, "GitSignsStagedChangedeleteCul", { fg = "#754119" })
  hi(0, "GitSignsStagedChangedeleteLn", { bg = "#4b4124" })
  hi(0, "GitSignsStagedChangedeleteNr", { fg = "#754119" })
  hi(0, "GitSignsStagedDelete", { fg = "#7c3a3f" })
  hi(0, "GitSignsStagedDeleteCul", { fg = "#7c3a3f" })
  hi(0, "GitSignsStagedDeleteNr", { fg = "#7c3a3f" })
  hi(0, "GitSignsStagedTopdelete", { fg = "#7c3a3f" })
  hi(0, "GitSignsStagedTopdeleteCul", { fg = "#7c3a3f" })
  hi(0, "GitSignsStagedTopdeleteNr", { fg = "#7c3a3f" })
  hi(0, "HeirlineCommand", { link = "StatusCommand" })
  hi(0, "HeirlineInactive", { link = "StatusInactive" })
  hi(0, "HeirlineInsert", { link = "StatusInsert" })
  hi(0, "HeirlineNormal", { link = "StatusNormal" })
  hi(0, "HeirlineReplace", { link = "StatusReplace" })
  hi(0, "HeirlineTerminal", { link = "StatusTerminal" })
  hi(0, "HeirlineVisual", { link = "StatusVisual" })
  hi(0, "HighlightURL", { underline = true })
  hi(0, "IblIndent", { fg = "#3a3e47" })
  hi(0, "IblScope", { fg = "#9b9fa9" })
  hi(0, "IblWhitespace", { fg = "#3a3e47" })
  hi(0, "Identifier", { fg = "#adb0bb" })
  hi(0, "Ignore", {})
  hi(0, "IlluminatedWordRead", { link = "LspReferenceRead" })
  hi(0, "IlluminatedWordText", { link = "LspReferenceText" })
  hi(0, "IlluminatedWordWrite", { link = "LspReferenceWrite" })
  hi(0, "IncSearch", { bg = "#cc83e3", fg = "#1a1d23" })
  hi(0, "Include", { fg = "#dd97f1" })
  hi(0, "IndentBlanklineChar", { fg = "#3a3e47" })
  hi(0, "IndentBlanklineContextChar", { fg = "#9b9fa9" })
  hi(0, "IndentBlanklineContextStart", { fg = "#adb0bb", underline = true })
  hi(0, "IndentBlanklineSpaceCharBlankline", { fg = "#3a3e47" })
  hi(0, "IndentBlanklineSpaceshar", { fg = "#3a3e47" })
  hi(0, "Italic", { italic = true })
  hi(0, "Keyword", { fg = "#dd97f1" })
  hi(0, "Label", { fg = "#5eb7ff" })
  hi(0, "LazyButton", { link = "CursorLine" })
  hi(0, "LazyButtonActive", { link = "Visual" })
  hi(0, "LazyComment", { link = "Comment" })
  hi(0, "LazyCommit", { bold = true, fg = "#494d56" })
  hi(0, "LazyCommitIssue", { fg = "#d09214" })
  hi(0, "LazyCommitScope", { italic = true })
  hi(0, "LazyCommitType", { bold = true, fg = "#50a4e9" })
  hi(0, "LazyDimmed", { link = "Conceal" })
  hi(0, "LazyDir", { fg = "#eb8332" })
  hi(0, "LazyH1", { bg = "#50a4e9", bold = true, fg = "#1a1d23" })
  hi(0, "LazyH2", { bold = true, fg = "#50a4e9" })
  hi(0, "LazyLocal", { fg = "#d09214" })
  hi(0, "LazyNoCond", { link = "DiagnosticWarn" })
  hi(0, "LazyNormal", { link = "NormalFloat" })
  hi(0, "LazyProgressDone", { fg = "#75ad47" })
  hi(0, "LazyProgressTodo", { link = "LineNr" })
  hi(0, "LazyProp", { link = "Conceal" })
  hi(0, "LazyReasonCmd", { fg = "#eb8332" })
  hi(0, "LazyReasonEvent", { fg = "#d09214" })
  hi(0, "LazyReasonFt", { fg = "#00b298" })
  hi(0, "LazyReasonImport", { fg = "#9b9fa9" })
  hi(0, "LazyReasonKeys", { fg = "#cc83e3" })
  hi(0, "LazyReasonPlugin", { fg = "#50a4e9" })
  hi(0, "LazyReasonRuntime", { fg = "#d09214" })
  hi(0, "LazyReasonSource", { fg = "#75ad47" })
  hi(0, "LazyReasonStart", { fg = "#f8747e" })
  hi(0, "LazySpecial", { fg = "#50a4e9" })
  hi(0, "LazyTaskError", { fg = "#f8747e" })
  hi(0, "LazyTaskOutput", { fg = "#9b9fa9" })
  hi(0, "LazyUrl", { fg = "#50a4e9", underline = true })
  hi(0, "LazyValue", { fg = "#75ad47" })
  hi(0, "LineNr", { fg = "#3a3e47" })
  hi(0, "LspCodeLens", { fg = "#3a3e47" })
  hi(0, "LspCodeLensSeparator", { fg = "#3a3e47" })
  hi(0, "LspReferenceRead", { bg = "#23272f" })
  hi(0, "LspReferenceText", { link = "LspReferenceRead" })
  hi(0, "LspReferenceWrite", { link = "LspReferenceRead" })
  hi(0, "Macro", { fg = "#f5983a" })
  hi(0, "MatchParen", { bold = true, fg = "#eb8332" })
  hi(0, "MiniIconsAzure", { fg = "#73c7ff" })
  hi(0, "MiniIconsBlue", { fg = "#50a4e9" })
  hi(0, "MiniIconsCyan", { fg = "#00b298" })
  hi(0, "MiniIconsGreen", { fg = "#75ad47" })
  hi(0, "MiniIconsGrey", { fg = "#9b9fa9" })
  hi(0, "MiniIconsOrange", { fg = "#eb8332" })
  hi(0, "MiniIconsPurple", { fg = "#cc83e3" })
  hi(0, "MiniIconsRed", { fg = "#f8747e" })
  hi(0, "MiniIconsYellow", { fg = "#d09214" })
  hi(0, "ModeMsg", { bold = true, fg = "#9b9fa9" })
  hi(0, "MoreMsg", { bold = true, fg = "#9b9fa9" })
  hi(0, "NeoTreeCursorLine", { link = "PmenuSel" })
  hi(0, "NeoTreeDirectoryIcon", { fg = "#50a4e9" })
  hi(0, "NeoTreeFileIcon", { fg = "#9b9fa9" })
  hi(0, "NeoTreeFileName", { fg = "#9b9fa9" })
  hi(0, "NeoTreeFileNameOpened", { fg = "#75ad47" })
  hi(0, "NeoTreeFloatBorder", { fg = "#14161b" })
  hi(0, "NeoTreeFloatTitle", { bg = "#16181d", bold = true, fg = "#50a4e9" })
  hi(0, "NeoTreeGitAdded", { fg = "#75ad47" })
  hi(0, "NeoTreeGitConflict", { fg = "#f8747e" })
  hi(0, "NeoTreeGitDeleted", { fg = "#494d56" })
  hi(0, "NeoTreeGitIgnored", { fg = "#9b9fa9" })
  hi(0, "NeoTreeGitModified", { fg = "#eb8332" })
  hi(0, "NeoTreeGitRenamed", { fg = "#eb8332" })
  hi(0, "NeoTreeGitStaged", { fg = "#00b298" })
  hi(0, "NeoTreeGitUnstaged", { fg = "#d09214" })
  hi(0, "NeoTreeGitUntracked", { fg = "#d09214" })
  hi(0, "NeoTreeIndentMarker", { fg = "#3a3e47" })
  hi(0, "NeoTreeNormal", { bg = "#16181d", fg = "#9b9fa9" })
  hi(0, "NeoTreeNormalNC", { bg = "#16181d", fg = "#9b9fa9" })
  hi(0, "NeoTreeRootName", { bold = true, fg = "#adb0bb" })
  hi(0, "NeoTreeSymbolicLinkTarget", { fg = "#00b298" })
  hi(0, "NeoTreeTabActive", { bg = "#16181d", bold = true, fg = "#adb0bb" })
  hi(0, "NeoTreeTabInactive", { bg = "#111317", fg = "#494d56" })
  hi(0, "NeoTreeTabSeparatorActive", { bg = "#16181d", fg = "#16181d" })
  hi(0, "NeoTreeTabSeparatorInactive", { bg = "#111317", fg = "#111317" })
  hi(0, "NeoTreeTitleBar", { bg = "#16181d", bold = true, fg = "#50a4e9" })
  hi(0, "NeoTreeVertSplit", { bg = "#1a1d23", fg = "#111317" })
  hi(0, "NeoTreeWinSeparator", { bg = "#1a1d23", bold = true, fg = "#111317" })
  hi(0, "NonText", { fg = "#3a3e47" })
  hi(0, "Normal", { bg = "#1a1d23", fg = "#adb0bb" })
  hi(0, "NormalFloat", { bg = "#14161b", fg = "#9b9fa9" })
  hi(0, "NormalNC", { bg = "#16181d", fg = "#adb0bb" })
  hi(0, "NotifyBackground", { bg = "#1a1d23", fg = "#9b9fa9" })
  hi(0, "NotifyDEBUGBody", { bg = "#16181d", fg = "#9b9fa9" })
  hi(0, "NotifyDEBUGBorder", { bg = "#16181d", fg = "#00b298" })
  hi(0, "NotifyDEBUGIcon", { bg = "#16181d", fg = "#00b298" })
  hi(0, "NotifyDEBUGTitle", { bg = "#16181d", fg = "#00b298" })
  hi(0, "NotifyERRORBody", { bg = "#16181d", fg = "#9b9fa9" })
  hi(0, "NotifyERRORBorder", { bg = "#16181d", fg = "#f8747e" })
  hi(0, "NotifyERRORIcon", { bg = "#16181d", fg = "#f8747e" })
  hi(0, "NotifyERRORTitle", { bg = "#16181d", fg = "#f8747e" })
  hi(0, "NotifyINFOBody", { bg = "#16181d", fg = "#9b9fa9" })
  hi(0, "NotifyINFOBorder", { bg = "#16181d", fg = "#75ad47" })
  hi(0, "NotifyINFOIcon", { bg = "#16181d", fg = "#75ad47" })
  hi(0, "NotifyINFOTitle", { bg = "#16181d", fg = "#75ad47" })
  hi(0, "NotifyLogTime", { bg = "#16181d", fg = "#494d56" })
  hi(0, "NotifyLogTitle", { bg = "#16181d", fg = "#50a4e9" })
  hi(0, "NotifyTRACEBody", { bg = "#16181d", fg = "#9b9fa9" })
  hi(0, "NotifyTRACEBorder", { fg = "#4f3552" })
  hi(0, "NotifyTRACEIcon", { bg = "#16181d", fg = "#cc83e3" })
  hi(0, "NotifyTRACERBorder", { bg = "#16181d", fg = "#cc83e3" })
  hi(0, "NotifyTRACETitle", { bg = "#16181d", fg = "#cc83e3" })
  hi(0, "NotifyWARNBody", { bg = "#16181d", fg = "#9b9fa9" })
  hi(0, "NotifyWARNBorder", { bg = "#16181d", fg = "#eb8332" })
  hi(0, "NotifyWARNIcon", { bg = "#16181d", fg = "#eb8332" })
  hi(0, "NotifyWARNTitle", { bg = "#16181d", fg = "#eb8332" })
  hi(0, "Number", { fg = "#f5983a" })
  hi(0, "Operator", { fg = "#adb0bb" })
  hi(0, "Pmenu", { bg = "#14161b", fg = "#9b9fa9" })
  hi(0, "PmenuSbar", { bg = "#14161b" })
  hi(0, "PmenuSel", { bg = "#26343f", blend = 0, bold = true })
  hi(0, "PmenuThumb", { bg = "#50a4e9", blend = 0 })
  hi(0, "PreCondit", { fg = "#5eb7ff" })
  hi(0, "PreProc", { fg = "#dfab25" })
  hi(0, "Question", { fg = "#cc83e3" })
  hi(0, "QuickFixLine", { bg = "#d09214", fg = "#1a1d23" })
  hi(0, "Repeat", { fg = "#dd97f1" })
  hi(0, "Search", { bg = "#26343f" })
  hi(0, "SignColumn", {})
  hi(0, "Special", { fg = "#5eb7ff" })
  hi(0, "SpecialChar", { fg = "#5eb7ff" })
  hi(0, "SpecialComment", { fg = "#3a3e47" })
  hi(0, "SpecialKey", { fg = "#9b9fa9" })
  hi(0, "SpellBad", { sp = "#f8747e", undercurl = true })
  hi(0, "SpellCap", { sp = "#d09214", undercurl = true })
  hi(0, "SpellLocal", { sp = "#50a4e9", undercurl = true })
  hi(0, "SpellRare", { sp = "#75ad47", undercurl = true })
  hi(0, "Statement", { fg = "#dd97f1" })
  hi(0, "StatusCommand", { bg = "#d09214", fg = "#111317" })
  hi(0, "StatusInactive", { bg = "#494d56", fg = "#111317" })
  hi(0, "StatusInsert", { bg = "#75ad47", fg = "#111317" })
  hi(0, "StatusLine", { bg = "#111317", fg = "#9b9fa9" })
  hi(0, "StatusLineNC", { fg = "#494d56" })
  hi(0, "StatusNormal", { bg = "#50a4e9", fg = "#111317" })
  hi(0, "StatusReplace", { bg = "#f8747e", fg = "#111317" })
  hi(0, "StatusTerminal", { link = "StatusInsert" })
  hi(0, "StatusVisual", { bg = "#cc83e3", fg = "#111317" })
  hi(0, "StorageClass", { fg = "#5eb7ff" })
  hi(0, "String", { fg = "#87c05f" })
  hi(0, "Structure", { fg = "#dfab25" })
  hi(0, "Substitute", { bg = "#f8747e", bold = true, fg = "#1a1d23" })
  hi(0, "TabLine", { bg = "#111317", fg = "#494d56" })
  hi(0, "TabLineFill", { bg = "#111317" })
  hi(0, "TabLineSel", { bg = "#1a1d23", bold = true, fg = "#adb0bb", italic = true })
  hi(0, "Tag", { fg = "#5eb7ff" })
  hi(0, "TelescopeBorder", { bg = "#14161b", fg = "#26343f" })
  hi(0, "TelescopeMatching", { bold = true, fg = "#e0e0ee" })
  hi(0, "TelescopeMultiIcon", { fg = "#50a4e9" })
  hi(0, "TelescopeMultiSelection", { fg = "#5eb7ff" })
  hi(0, "TelescopeNormal", { bg = "#14161b" })
  hi(0, "TelescopePreviewBorder", { bg = "#14161b", fg = "#14161b" })
  hi(0, "TelescopePreviewNormal", { bg = "#14161b" })
  hi(0, "TelescopePreviewTitle", { bg = "#87c05f", fg = "#14161b" })
  hi(0, "TelescopePromptBorder", { bg = "#26343f", fg = "#26343f" })
  hi(0, "TelescopePromptNormal", { bg = "#26343f", fg = "#9b9fa9" })
  hi(0, "TelescopePromptPrefix", { bg = "#26343f", fg = "#f8747e" })
  hi(0, "TelescopePromptTitle", { bg = "#f8747e", fg = "#14161b" })
  hi(0, "TelescopeResultsBorder", { bg = "#14161b", fg = "#14161b" })
  hi(0, "TelescopeResultsNormal", { bg = "#14161b" })
  hi(0, "TelescopeResultsTitle", { bg = "#14161b", fg = "#14161b" })
  hi(0, "TelescopeSelection", { link = "PmenuSel" })
  hi(0, "TelescopeSelectionCaret", { fg = "#50a4e9" })
  hi(0, "Terminal", { bg = "#1a1d23", fg = "#9b9fa9" })
  hi(0, "Title", { bg = "#16181d", bold = true, fg = "#50a4e9" })
  hi(0, "Todo", { fg = "#d09214" })
  hi(0, "TodoBgFIX", { bg = "#f8747e", bold = true, fg = "#1a1d23" })
  hi(0, "TodoBgHACK", { bg = "#d09214", bold = true, fg = "#1a1d23" })
  hi(0, "TodoBgNOTE", { bg = "#00b298", bold = true, fg = "#adb0bb" })
  hi(0, "TodoBgPERF", { bg = "#adb0bb", bold = true, fg = "#1a1d23" })
  hi(0, "TodoBgTEST", { bg = "#adb0bb", bold = true, fg = "#1a1d23" })
  hi(0, "TodoBgTODO", { bg = "#50a4e9", bold = true, fg = "#1a1d23" })
  hi(0, "TodoBgWARN", { bg = "#d09214", bold = true, fg = "#1a1d23" })
  hi(0, "TodoFgFIX", { fg = "#f8747e" })
  hi(0, "TodoFgHACK", { fg = "#d09214" })
  hi(0, "TodoFgNOTE", { fg = "#00b298" })
  hi(0, "TodoFgPERF", { fg = "#adb0bb" })
  hi(0, "TodoFgTEST", { fg = "#adb0bb" })
  hi(0, "TodoFgTODO", { fg = "#50a4e9" })
  hi(0, "TodoFgWARN", { fg = "#d09214" })
  hi(0, "TodoSignFIX", { fg = "#f8747e" })
  hi(0, "TodoSignHACK", { fg = "#d09214" })
  hi(0, "TodoSignNOTE", { fg = "#00b298" })
  hi(0, "TodoSignPERF", { fg = "#adb0bb" })
  hi(0, "TodoSignTEST", { fg = "#adb0bb" })
  hi(0, "TodoSignTODO", { fg = "#50a4e9" })
  hi(0, "TodoSignWARN", { fg = "#d09214" })
  hi(0, "Type", { fg = "#5eb7ff" })
  hi(0, "Typedef", { fg = "#dfab25" })
  hi(0, "UfoFoldedFg", { fg = "#adb0bb" })
  hi(0, "Underlined", { fg = "#4ac2b8", underline = true })
  hi(0, "VertSplit", { bg = "#1a1d23", fg = "#111317" })
  hi(0, "Visual", { bg = "#26343f" })
  hi(0, "VisualNOS", { fg = "#26343f" })
  hi(0, "WarningMsg", { fg = "#d09214" })
  hi(0, "WhichKey", { fg = "#00b298" })
  hi(0, "WhichKeyBorder", { link = "FloatBorder" })
  hi(0, "WhichKeyDesc", { fg = "#cc83e3" })
  hi(0, "WhichKeyFloat", { link = "NormalFloat" })
  hi(0, "WhichKeyGroup", { fg = "#50a4e9" })
  hi(0, "WhichKeySeparator", { fg = "#3a3e47" })
  hi(0, "WhichKeyValue", { fg = "#adb0bb" })
  hi(0, "WildMenu", { bg = "#50a4e9", fg = "#1a1d23" })
  hi(0, "WinBar", { fg = "#797d87" })
  hi(0, "WinBarNC", { bg = "#16181d", fg = "#494d56" })
  hi(0, "WinSeparator", { bg = "#1a1d23", fg = "#111317" })
  hi(0, "WindowPickerStatusLine", { fg = "#f8747e" })
  hi(0, "WindowPickerStatusLineNC", { fg = "#f8747e" })
  hi(0, "WindowPickerWinBar", { fg = "#f8747e" })
  hi(0, "WindowPickerWinBarNC", { fg = "#f8747e" })
  hi(0, "lCursor", { link = "Cursor" })

  -- Terminal colors
  local g = vim.g

  g.terminal_color_0 = "#111317"
  g.terminal_color_1 = "#ff838b"
  g.terminal_color_2 = "#87c05f"
  g.terminal_color_3 = "#dfab25"
  g.terminal_color_4 = "#5eb7ff"
  g.terminal_color_5 = "#dd97f1"
  g.terminal_color_6 = "#4ac2b8"
  g.terminal_color_7 = "#9b9fa9"
  g.terminal_color_8 = "#34363a"
  g.terminal_color_9 = "#ffa6ae"
  g.terminal_color_10 = "#aae382"
  g.terminal_color_11 = "#ffce48"
  g.terminal_color_12 = "#81daff"
  g.terminal_color_13 = "#ffbaff"
  g.terminal_color_14 = "#6de5db"
  g.terminal_color_15 = "#d0d3de"
end

if vim.o.background == "light" then
  hi(0, "@annotation", { fg = "#7300b8" })
  hi(0, "@attribute", { fg = "#7300b8" })
  hi(0, "@attribute.builtin", { link = "@attribute" })
  hi(0, "@character.special", { link = "SpecialChar" })
  hi(0, "@class", { fg = "#00508a" })
  hi(0, "@comment.documentation", { link = "@comment" })
  hi(0, "@comment.error", { bg = "#e72f1f", fg = "#f7f8f8" })
  hi(0, "@comment.hint", { bg = "#3f8cea", fg = "#f7f8f8" })
  hi(0, "@comment.info", { bg = "#21b386", fg = "#f7f8f8" })
  hi(0, "@comment.todo", { bg = "#e69400", fg = "#f7f8f8" })
  hi(0, "@comment.warning", { bg = "#f0740a", fg = "#f7f8f8" })
  hi(0, "@conditional", { link = "@keyword.conditional" })
  hi(0, "@conditional.ternary", { link = "@keyword.conditional.ternary" })
  hi(0, "@constant.builtin", { link = "@constant" })
  hi(0, "@constant.macro", { link = "@constant" })
  hi(0, "@constant.rust", { fg = "#00615b" })
  hi(0, "@constructor", { link = "@function" })
  hi(0, "@constructor.lua", { fg = "#a34500" })
  hi(0, "@constructor.tsx", { fg = "#9e007c" })
  hi(0, "@constructor.typescript", { fg = "#9e007c" })
  hi(0, "@debug", { link = "@keyword.debug" })
  hi(0, "@decorator", { fg = "#a34500" })
  hi(0, "@define", { link = "@keyword.directive.define" })
  hi(0, "@diff.delta", { link = "DiffChange" })
  hi(0, "@diff.minus", { link = "DiffDelete" })
  hi(0, "@diff.plus", { link = "DiffAdded" })
  hi(0, "@enum", { fg = "#00615b" })
  hi(0, "@enumMember", { fg = "#a34500" })
  hi(0, "@error", { link = "Error" })
  hi(0, "@event", { fg = "#a34500" })
  hi(0, "@exception", { link = "@keyword.exception" })
  hi(0, "@field", { link = "@variable.member" })
  hi(0, "@field.yaml", { fg = "#990000" })
  hi(0, "@float", { link = "@number.float" })
  hi(0, "@function.builtin", { fg = "#00615b" })
  hi(0, "@function.call", { link = "@function" })
  hi(0, "@function.macro", { fg = "#7300b8" })
  hi(0, "@function.macro.rust", { fg = "#990000" })
  hi(0, "@function.method", { link = "@function" })
  hi(0, "@function.method.call", { link = "@function.method" })
  hi(0, "@function.method.call.php", { link = "Function" })
  hi(0, "@function.method.php", { link = "Function" })
  hi(0, "@include", { link = "@keyword.include" })
  hi(0, "@interface", { fg = "#a34500" })
  hi(0, "@keyword.conditional", { link = "Conditional" })
  hi(0, "@keyword.conditional.ternary", { link = "@keyword.conditional" })
  hi(0, "@keyword.corotine", { link = "Keyword" })
  hi(0, "@keyword.debug", { link = "Debug" })
  hi(0, "@keyword.directive", { link = "Keyword" })
  hi(0, "@keyword.directive.define", { link = "Keyword" })
  hi(0, "@keyword.exception", { link = "Exception" })
  hi(0, "@keyword.export", { link = "@keyword" })
  hi(0, "@keyword.function", { link = "Keyword" })
  hi(0, "@keyword.import", { link = "Include" })
  hi(0, "@keyword.modifier", { link = "Structure" })
  hi(0, "@keyword.operator", { link = "Keyword" })
  hi(0, "@keyword.repeat", { link = "Repeat" })
  hi(0, "@keyword.return", { link = "Keyword" })
  hi(0, "@keyword.storage", { link = "StorageClass" })
  hi(0, "@keyword.type", { link = "Typedef" })
  hi(0, "@label.json", { fg = "#00508a" })
  hi(0, "@literal.markdown", { fg = "#345e00" })
  hi(0, "@lsp.type.boolean", { link = "@boolean" })
  hi(0, "@lsp.type.builtinType", { link = "@type.builtin" })
  hi(0, "@lsp.type.comment", { link = "@comment" })
  hi(0, "@lsp.type.enum", { link = "@type" })
  hi(0, "@lsp.type.enumMember", { link = "@constant" })
  hi(0, "@lsp.type.escapeSequence", { link = "@string.escape" })
  hi(0, "@lsp.type.formatSpecifier", { link = "@punctuation.special" })
  hi(0, "@lsp.type.function.rust", { fg = "#4f4f4f" })
  hi(0, "@lsp.type.interface", { link = "@interface" })
  hi(0, "@lsp.type.keyword", { link = "@keyword" })
  hi(0, "@lsp.type.macro.rust", { link = "@function.macro.rust" })
  hi(0, "@lsp.type.namespace", { link = "@namespace" })
  hi(0, "@lsp.type.namespace.rust", { link = "@namespace.rust" })
  hi(0, "@lsp.type.number", { link = "@number" })
  hi(0, "@lsp.type.operator", { link = "@operator" })
  hi(0, "@lsp.type.parameter", { link = "@parameter" })
  hi(0, "@lsp.type.property", { link = "@property" })
  hi(0, "@lsp.type.selfKeyword", { link = "@variable.builtin" })
  hi(0, "@lsp.type.typeAlias", { link = "@type.definition" })
  hi(0, "@lsp.type.unresolvedReference", { link = "@error" })
  hi(0, "@lsp.type.variable", { link = "@variable" })
  hi(0, "@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
  hi(0, "@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
  hi(0, "@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
  hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
  hi(0, "@lsp.typemod.function.defaultLibrary.rust", { fg = "#4f4f4f" })
  hi(0, "@lsp.typemod.function.global", { link = "@function.builtin" })
  hi(0, "@lsp.typemod.keyword.async", { link = "@keyword.coroutine" })
  hi(0, "@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
  hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
  hi(0, "@lsp.typemod.method.reference", { link = "@function" })
  hi(0, "@lsp.typemod.method.trait", { link = "@function" })
  hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
  hi(0, "@lsp.typemod.selfKeyword.defaultLibrary", { link = "@keyword" })
  hi(0, "@lsp.typemod.string.injected", { link = "@string" })
  hi(0, "@lsp.typemod.type.defaultLibrary", { link = "@type.builtin" })
  hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
  hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
  hi(0, "@lsp.typemod.variable.readonly", { link = "@constant" })
  hi(0, "@markup.environment", { fg = "#a34500" })
  hi(0, "@markup.heading", { bold = true, fg = "#4f4f4f" })
  hi(0, "@markup.heading.1.markdown", { bold = true, fg = "#9e007c" })
  hi(0, "@markup.heading.2.markdown", { bold = true, fg = "#00508a" })
  hi(0, "@markup.heading.3.markdown", { bold = true, fg = "#00615b" })
  hi(0, "@markup.heading.4.markdown", { bold = true, fg = "#345e00" })
  hi(0, "@markup.heading.5.markdown", { bold = true, fg = "#7300b8" })
  hi(0, "@markup.italic", { fg = "#4f4f4f", italic = true })
  hi(0, "@markup.link", { bold = true, fg = "#7300b8" })
  hi(0, "@markup.link.label", { link = "String" })
  hi(0, "@markup.link.url", { fg = "#00508a", italic = true, underline = true })
  hi(0, "@markup.list", { link = "Special" })
  hi(0, "@markup.list.checked", { bg = "#42ad17", fg = "#f7f8f8" })
  hi(0, "@markup.list.unchecked", { bg = "#671ff0", fg = "#f7f8f8" })
  hi(0, "@markup.math", { fg = "#00508a" })
  hi(0, "@markup.quote", { fg = "#4f4f4f", italic = true })
  hi(0, "@markup.raw", { fg = "#990000" })
  hi(0, "@markup.raw.block", { fg = "#4f4f4f" })
  hi(0, "@markup.strikethrough", { fg = "#4f4f4f", strikethrough = true })
  hi(0, "@markup.strong", { bold = true, fg = "#4f4f4f" })
  hi(0, "@markup.underline", { link = "Underline" })
  hi(0, "@method", { link = "@function" })
  hi(0, "@method.call", { link = "@function.method" })
  hi(0, "@method.call.php", { link = "@function.method.call.php" })
  hi(0, "@method.php", { link = "@function.method.php" })
  hi(0, "@modifier", { fg = "#a34500" })
  hi(0, "@module", { link = "Keyword" })
  hi(0, "@module.builtin", { fg = "#7300b8" })
  hi(0, "@module.rust", { fg = "#9e007c" })
  hi(0, "@namespace", { link = "@module" })
  hi(0, "@namespace.builtin", { link = "@module.builtin" })
  hi(0, "@namespace.rust", { link = "@module.rust" })
  hi(0, "@none.markdown", { fg = "#4f4f4f" })
  hi(0, "@number.css", { fg = "#00615b" })
  hi(0, "@number.float", { link = "Float" })
  hi(0, "@parameter", { link = "@variable.parameter" })
  hi(0, "@preproc", { link = "@keyword.directive" })
  hi(0, "@property", { fg = "#990000" })
  hi(0, "@property.class.css", { fg = "#7300b8" })
  hi(0, "@property.cpp", { fg = "#a34500" })
  hi(0, "@property.css", { fg = "#a34500" })
  hi(0, "@property.id.css", { fg = "#00508a" })
  hi(0, "@property.toml", { fg = "#990000" })
  hi(0, "@punctuation.bracket", { fg = "#4f4f4f" })
  hi(0, "@punctuation.delimiter", { fg = "#4f4f4f" })
  hi(0, "@punctuation.delimiter.markdown", { link = "@punctuation.delimiter" })
  hi(0, "@punctuation.special", { fg = "#4f4f4f" })
  hi(0, "@punctuation.special.markdown", { link = "@punctuation.special" })
  hi(0, "@punctuation.special.rust", { fg = "#9e007c" })
  hi(0, "@regexp", { fg = "#00615b" })
  hi(0, "@repeat", { link = "@keyword.repeat" })
  hi(0, "@storageclass", { link = "@keyword.storageclass" })
  hi(0, "@string.documentation", { link = "String" })
  hi(0, "@string.escape", { fg = "#990000" })
  hi(0, "@string.plain.css", { fg = "#345e00" })
  hi(0, "@string.regex", { link = "@string.regexp" })
  hi(0, "@string.regexp", { link = "String" })
  hi(0, "@string.special", { link = "String" })
  hi(0, "@string.special.path", { link = "String" })
  hi(0, "@string.special.symbol", { link = "String" })
  hi(0, "@string.special.symbol.ruby", { fg = "#a34500" })
  hi(0, "@string.special.url", { link = "@markup.link.url" })
  hi(0, "@struct", { fg = "#00508a" })
  hi(0, "@symbol", { link = "@string.special.symbol" })
  hi(0, "@symbol.ruby", { link = "@string.special.symbol.ruby" })
  hi(0, "@tag", { fg = "#990000" })
  hi(0, "@tag.attribute", { fg = "#00615b" })
  hi(0, "@tag.attribute.tsx", { fg = "#9e007c", italic = true })
  hi(0, "@tag.delimiter", { fg = "#4f4f4f" })
  hi(0, "@text", { fg = "#4f4f4f" })
  hi(0, "@text.checked", { link = "@markup.list.checked" })
  hi(0, "@text.danger", { link = "@comment.error" })
  hi(0, "@text.diff.add", { link = "@diff.plus" })
  hi(0, "@text.diff.delete", { link = "@diff.minus" })
  hi(0, "@text.emphasis", { link = "@markup.emphasis" })
  hi(0, "@text.environment", { link = "@markup.environment" })
  hi(0, "@text.environment.name", { link = "@markup.environment" })
  hi(0, "@text.literal", { link = "@markup.raw" })
  hi(0, "@text.math", { link = "@markup.math" })
  hi(0, "@text.note", { link = "@comment.hint" })
  hi(0, "@text.quote", { link = "@markup.quote" })
  hi(0, "@text.reference", { link = "@markup.link" })
  hi(0, "@text.strike", { link = "@markup.strikethrough" })
  hi(0, "@text.strong", { link = "@markup.strong" })
  hi(0, "@text.title", { link = "@markup.heading" })
  hi(0, "@text.title.1.markdown", { link = "@markup.heading.1.markdown" })
  hi(0, "@text.title.2.markdown", { link = "@markup.heading.2.markdown" })
  hi(0, "@text.title.3.markdown", { link = "@markup.heading.3.markdown" })
  hi(0, "@text.title.4.markdown", { link = "@markup.heading.4.markdown" })
  hi(0, "@text.title.5.markdown", { link = "@markup.heading.5.markdown" })
  hi(0, "@text.todo", { link = "@comment.todo" })
  hi(0, "@text.todo.checked", { link = "@text.checked" })
  hi(0, "@text.todo.danger", { link = "@text.danger" })
  hi(0, "@text.todo.note", { link = "@text.note" })
  hi(0, "@text.todo.unchecked", { link = "@text.unchecked" })
  hi(0, "@text.todo.warning", { link = "@text.warning" })
  hi(0, "@text.unchecked", { link = "@markup.list.unchecked" })
  hi(0, "@text.underline", { link = "@markup.underline" })
  hi(0, "@text.uri", { link = "@markup.link.url" })
  hi(0, "@text.warning", { link = "@comment.warning" })
  hi(0, "@title.markdown", { link = "markup.heading" })
  hi(0, "@type.builtin", { fg = "#7300b8" })
  hi(0, "@type.css", { fg = "#a34500" })
  hi(0, "@type.definition", { link = "@type" })
  hi(0, "@type.qualifier", { link = "@type" })
  hi(0, "@type.qualifier.php", { link = "Keyword" })
  hi(0, "@type.qualifier.typescript", { link = "Keyword" })
  hi(0, "@type.rust", { fg = "#00615b" })
  hi(0, "@type.tag.css", { fg = "#9e007c" })
  hi(0, "@typeParameter", { fg = "#7300b8" })
  hi(0, "@variable", { link = "Identifier" })
  hi(0, "@variable.builtin", { fg = "#00615b" })
  hi(0, "@variable.lua", { link = "@variable" })
  hi(0, "@variable.member", { link = "@property" })
  hi(0, "@variable.parameter", { fg = "#a34500" })
  hi(0, "@variable.parameter.builtin", { link = "@variable.parameter" })
  hi(0, "AerialArrayIcon", { link = "@constant" })
  hi(0, "AerialBooleanIcon", { link = "@boolean" })
  hi(0, "AerialClassIcon", { link = "@type" })
  hi(0, "AerialConstantIcon", { link = "@constant" })
  hi(0, "AerialConstructorIcon", { link = "@constructor" })
  hi(0, "AerialEnumIcon", { link = "@type" })
  hi(0, "AerialEnumMemberIcon", { link = "@field" })
  hi(0, "AerialEventIcon", { link = "@type" })
  hi(0, "AerialFieldIcon", { link = "@field" })
  hi(0, "AerialFileIcon", { link = "@text.uri" })
  hi(0, "AerialFunctionIcon", { link = "@function" })
  hi(0, "AerialGuide", { fg = "#b5b9bd" })
  hi(0, "AerialInterfaceIcon", { link = "@type" })
  hi(0, "AerialKeyIcon", { link = "@type" })
  hi(0, "AerialLine", { fg = "#671ff0" })
  hi(0, "AerialMethodIcon", { link = "@method" })
  hi(0, "AerialModuleIcon", { link = "@namespace" })
  hi(0, "AerialNamespaceIcon", { link = "@namespace" })
  hi(0, "AerialNormal", { fg = "#737474" })
  hi(0, "AerialNullIcon", { link = "@type" })
  hi(0, "AerialNumberIcon", { link = "@number" })
  hi(0, "AerialObjectIcon", { link = "@type" })
  hi(0, "AerialOperatorIcon", { link = "@operator" })
  hi(0, "AerialPackageIcon", { link = "@namespace" })
  hi(0, "AerialPropertyIcon", { link = "@property" })
  hi(0, "AerialStringIcon", { link = "@string" })
  hi(0, "AerialStructIcon", { link = "@type" })
  hi(0, "AerialTypeIcon", { link = "@type" })
  hi(0, "AerialTypeParameterIcon", { link = "@parameter" })
  hi(0, "AerialVariableIcon", { link = "@variable" })
  hi(0, "Bold", { bold = true })
  hi(0, "Boolean", { fg = "#a34500" })
  hi(0, "Character", { fg = "#345e00" })
  hi(0, "CmpItemAbbr", { fg = "#737474" })
  hi(0, "CmpItemAbbrDeprecated", { fg = "#990000", strikethrough = true })
  hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#17191c" })
  hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#17191c" })
  hi(0, "CmpItemKimdStruct", { link = "@type" })
  hi(0, "CmpItemKind", { fg = "#7300b8" })
  hi(0, "CmpItemKindArray", { bg = "#f0740a", fg = "#e1e2e3" })
  hi(0, "CmpItemKindBoolean", { bg = "#f0740a", fg = "#e1e2e3" })
  hi(0, "CmpItemKindClass", { bg = "#671ff0", fg = "#e1e2e3" })
  hi(0, "CmpItemKindColor", { bg = "#e72f1f", fg = "#e1e2e3" })
  hi(0, "CmpItemKindConstant", { bg = "#f0740a", fg = "#e1e2e3" })
  hi(0, "CmpItemKindConstructor", { bg = "#62afff", fg = "#e1e2e3" })
  hi(0, "CmpItemKindEnum", { bg = "#671ff0", fg = "#e1e2e3" })
  hi(0, "CmpItemKindEnumMember", { bg = "#e69400", fg = "#e1e2e3" })
  hi(0, "CmpItemKindEvent", { bg = "#e72f1f", fg = "#e1e2e3" })
  hi(0, "CmpItemKindField", { bg = "#e69400", fg = "#e1e2e3" })
  hi(0, "CmpItemKindFile", { bg = "#3f8cea", fg = "#e1e2e3" })
  hi(0, "CmpItemKindFolder", { bg = "#3f8cea", fg = "#e1e2e3" })
  hi(0, "CmpItemKindFunction", { bg = "#62afff", fg = "#e1e2e3" })
  hi(0, "CmpItemKindInterface", { bg = "#671ff0", fg = "#e1e2e3" })
  hi(0, "CmpItemKindKey", { bg = "#e69400", fg = "#e1e2e3" })
  hi(0, "CmpItemKindKeyword", { bg = "#21b386", fg = "#e1e2e3" })
  hi(0, "CmpItemKindMethod", { bg = "#62afff", fg = "#e1e2e3" })
  hi(0, "CmpItemKindModule", { bg = "#671ff0", fg = "#e1e2e3" })
  hi(0, "CmpItemKindNamespace", { bg = "#e72f1f", fg = "#e1e2e3" })
  hi(0, "CmpItemKindNull", { bg = "#737474", fg = "#e1e2e3" })
  hi(0, "CmpItemKindNumber", { bg = "#f0740a", fg = "#e1e2e3" })
  hi(0, "CmpItemKindObject", { bg = "#737474", fg = "#e1e2e3" })
  hi(0, "CmpItemKindOperator", { bg = "#21b386", fg = "#e1e2e3" })
  hi(0, "CmpItemKindPackage", { bg = "#671ff0", fg = "#e1e2e3" })
  hi(0, "CmpItemKindProperty", { bg = "#e69400", fg = "#e1e2e3" })
  hi(0, "CmpItemKindReference", { bg = "#21b386", fg = "#e1e2e3" })
  hi(0, "CmpItemKindSnippet", { bg = "#42ad17", fg = "#e1e2e3" })
  hi(0, "CmpItemKindString", { bg = "#42ad17", fg = "#e1e2e3" })
  hi(0, "CmpItemKindStruct", { bg = "#671ff0", fg = "#e1e2e3" })
  hi(0, "CmpItemKindText", { bg = "#42ad17", fg = "#e1e2e3" })
  hi(0, "CmpItemKindTypeParameter", { bg = "#21b386", fg = "#e1e2e3" })
  hi(0, "CmpItemKindUnit", { bg = "#21b386", fg = "#e1e2e3" })
  hi(0, "CmpItemKindValue", { bg = "#3f8cea", fg = "#e1e2e3" })
  hi(0, "CmpItemKindVariable", { bg = "#21b386", fg = "#e1e2e3" })
  hi(0, "ColorColumn", { bg = "#eaebeb" })
  hi(0, "Comment", { fg = "#8b9297", italic = true })
  hi(0, "Conceal", { fg = "#aeb3b6" })
  hi(0, "Conditional", { fg = "#9e007c" })
  hi(0, "Constant", { fg = "#7300b8" })
  hi(0, "CurSearch", { link = "IncSearch" })
  hi(0, "Cursor", { bg = "#737474", fg = "#f7f8f8" })
  hi(0, "CursorColumn", { bg = "#eaebeb" })
  hi(0, "CursorLine", { bg = "#eaebeb" })
  hi(0, "CursorLineNr", { fg = "#424446" })
  hi(0, "DashboardCenter", { fg = "#00508a" })
  hi(0, "DashboardFooter", { fg = "#00615b" })
  hi(0, "DashboardHeader", { fg = "#00615b" })
  hi(0, "DashboardShortcut", { fg = "#7300b8" })
  hi(0, "Debug", { fg = "#3f8cea" })
  hi(0, "Define", { fg = "#9e007c" })
  hi(0, "Delimiter", { fg = "#00508a" })
  hi(0, "DiagnosticError", { fg = "#e72f1f" })
  hi(0, "DiagnosticHint", { fg = "#21b386" })
  hi(0, "DiagnosticInfo", { fg = "#3f8cea" })
  hi(0, "DiagnosticOk", { fg = "#42ad17" })
  hi(0, "DiagnosticUnderlineError", { sp = "#e72f1f", undercurl = true })
  hi(0, "DiagnosticUnderlineHint", { sp = "#21b386", undercurl = true })
  hi(0, "DiagnosticUnderlineInfo", { sp = "#3f8cea", undercurl = true })
  hi(0, "DiagnosticUnderlineOk", { sp = "#42ad17", undercurl = true })
  hi(0, "DiagnosticUnderlineWarn", { sp = "#e69400", undercurl = true })
  hi(0, "DiagnosticWarn", { fg = "#e69400" })
  hi(0, "DiffAdd", { bg = "#c6d2ba" })
  hi(0, "DiffAdded", { fg = "#345e00" })
  hi(0, "DiffChange", { bg = "#d6bae8" })
  hi(0, "DiffChanged", { fg = "#00508a" })
  hi(0, "DiffDelete", { bg = "#e0baba" })
  hi(0, "DiffFile", { fg = "#00508a" })
  hi(0, "DiffIndexLine", { fg = "#00615b" })
  hi(0, "DiffLine", { fg = "#4f4f4f" })
  hi(0, "DiffNewFile", { fg = "#345e00" })
  hi(0, "DiffOldFile", { fg = "#a34500" })
  hi(0, "DiffRemoved", { fg = "#990000" })
  hi(0, "DiffText", { bg = "#cfaee5" })
  hi(0, "Directory", { fg = "#3f8cea" })
  hi(0, "EndOfBuffer", { fg = "#b5b9bd" })
  hi(0, "Error", { fg = "#e72f1f" })
  hi(0, "ErrorMsg", { fg = "#990000" })
  hi(0, "Exception", { fg = "#9e007c" })
  hi(0, "Float", { fg = "#7300b8" })
  hi(0, "FloatBorder", { bg = "#e1e2e3", fg = "#671ff0" })
  hi(0, "FloatTitle", { bg = "#e1e2e3", bold = true, fg = "#671ff0" })
  hi(0, "FoldColumn", { fg = "#b5b9bd" })
  hi(0, "Folded", { fg = "#b5b9bd" })
  hi(0, "Function", { fg = "#00508a" })
  hi(0, "GitSignsAdd", { fg = "#42ad17" })
  hi(0, "GitSignsChange", { fg = "#f0740a" })
  hi(0, "GitSignsDelete", { fg = "#e72f1f" })
  hi(0, "HeirlineCommand", { link = "StatusCommand" })
  hi(0, "HeirlineInactive", { link = "StatusInactive" })
  hi(0, "HeirlineInsert", { link = "StatusInsert" })
  hi(0, "HeirlineNormal", { link = "StatusNormal" })
  hi(0, "HeirlineReplace", { link = "StatusReplace" })
  hi(0, "HeirlineTerminal", { link = "StatusTerminal" })
  hi(0, "HeirlineVisual", { link = "StatusVisual" })
  hi(0, "HighlightURL", { underline = true })
  hi(0, "IblIndent", { fg = "#b5b9bd" })
  hi(0, "IblScope", { fg = "#737474" })
  hi(0, "IblWhitespace", { fg = "#b5b9bd" })
  hi(0, "Identifier", { fg = "#4f4f4f" })
  hi(0, "Ignore", {})
  hi(0, "IlluminatedWordRead", { link = "LspReferenceRead" })
  hi(0, "IlluminatedWordText", { link = "LspReferenceText" })
  hi(0, "IlluminatedWordWrite", { link = "LspReferenceWrite" })
  hi(0, "IncSearch", { bg = "#671ff0", fg = "#f7f8f8" })
  hi(0, "Include", { fg = "#9e007c" })
  hi(0, "IndentBlanklineChar", { fg = "#b5b9bd" })
  hi(0, "IndentBlanklineContextChar", { fg = "#737474" })
  hi(0, "IndentBlanklineContextStart", { fg = "#424446", underline = true })
  hi(0, "IndentBlanklineSpaceCharBlankline", { fg = "#b5b9bd" })
  hi(0, "IndentBlanklineSpaceshar", { fg = "#b5b9bd" })
  hi(0, "Italic", { italic = true })
  hi(0, "Keyword", { fg = "#9e007c" })
  hi(0, "Label", { fg = "#00508a" })
  hi(0, "LazyButton", { link = "CursorLine" })
  hi(0, "LazyButtonActive", { link = "Visual" })
  hi(0, "LazyComment", { link = "Comment" })
  hi(0, "LazyCommit", { bold = true, fg = "#aeb3b6" })
  hi(0, "LazyCommitIssue", { fg = "#e69400" })
  hi(0, "LazyCommitScope", { italic = true })
  hi(0, "LazyCommitType", { bold = true, fg = "#671ff0" })
  hi(0, "LazyDimmed", { link = "Conceal" })
  hi(0, "LazyDir", { fg = "#f0740a" })
  hi(0, "LazyH1", { bg = "#671ff0", bold = true, fg = "#f7f8f8" })
  hi(0, "LazyH2", { bold = true, fg = "#671ff0" })
  hi(0, "LazyLocal", { fg = "#e69400" })
  hi(0, "LazyNoCond", { link = "DiagnosticWarn" })
  hi(0, "LazyNormal", { link = "NormalFloat" })
  hi(0, "LazyProgressDone", { fg = "#42ad17" })
  hi(0, "LazyProgressTodo", { link = "LineNr" })
  hi(0, "LazyProp", { link = "Conceal" })
  hi(0, "LazyReasonCmd", { fg = "#f0740a" })
  hi(0, "LazyReasonEvent", { fg = "#e69400" })
  hi(0, "LazyReasonFt", { fg = "#21b386" })
  hi(0, "LazyReasonImport", { fg = "#737474" })
  hi(0, "LazyReasonKeys", { fg = "#671ff0" })
  hi(0, "LazyReasonPlugin", { fg = "#3f8cea" })
  hi(0, "LazyReasonRuntime", { fg = "#e69400" })
  hi(0, "LazyReasonSource", { fg = "#42ad17" })
  hi(0, "LazyReasonStart", { fg = "#e72f1f" })
  hi(0, "LazySpecial", { fg = "#3f8cea" })
  hi(0, "LazyTaskError", { fg = "#e72f1f" })
  hi(0, "LazyTaskOutput", { fg = "#737474" })
  hi(0, "LazyUrl", { fg = "#3f8cea", underline = true })
  hi(0, "LazyValue", { fg = "#42ad17" })
  hi(0, "LineNr", { fg = "#b5b9bd" })
  hi(0, "LspCodeLens", { fg = "#b5b9bd" })
  hi(0, "LspCodeLensSeparator", { fg = "#b5b9bd" })
  hi(0, "LspReferenceRead", { bg = "#dadbdd" })
  hi(0, "LspReferenceText", { link = "LspReferenceRead" })
  hi(0, "LspReferenceWrite", { link = "LspReferenceRead" })
  hi(0, "Macro", { fg = "#a34500" })
  hi(0, "MatchParen", { bold = true, fg = "#f0740a" })
  hi(0, "MiniIconsAzure", { fg = "#62afff" })
  hi(0, "MiniIconsBlue", { fg = "#3f8cea" })
  hi(0, "MiniIconsCyan", { fg = "#21b386" })
  hi(0, "MiniIconsGreen", { fg = "#42ad17" })
  hi(0, "MiniIconsGrey", { fg = "#737474" })
  hi(0, "MiniIconsOrange", { fg = "#f0740a" })
  hi(0, "MiniIconsPurple", { fg = "#671ff0" })
  hi(0, "MiniIconsRed", { fg = "#e72f1f" })
  hi(0, "MiniIconsYellow", { fg = "#e69400" })
  hi(0, "ModeMsg", { bold = true, fg = "#737474" })
  hi(0, "MoreMsg", { bold = true, fg = "#737474" })
  hi(0, "NeoTreeCursorLine", { link = "PmenuSel" })
  hi(0, "NeoTreeDirectoryIcon", { fg = "#3f8cea" })
  hi(0, "NeoTreeFileIcon", { fg = "#737474" })
  hi(0, "NeoTreeFileName", { fg = "#737474" })
  hi(0, "NeoTreeFileNameOpened", { fg = "#42ad17" })
  hi(0, "NeoTreeFloatBorder", { fg = "#e1e2e3" })
  hi(0, "NeoTreeFloatTitle", { bg = "#f0f0f1", bold = true, fg = "#671ff0" })
  hi(0, "NeoTreeGitAdded", { fg = "#42ad17" })
  hi(0, "NeoTreeGitConflict", { fg = "#e72f1f" })
  hi(0, "NeoTreeGitDeleted", { fg = "#aeb3b6" })
  hi(0, "NeoTreeGitIgnored", { fg = "#737474" })
  hi(0, "NeoTreeGitModified", { fg = "#f0740a" })
  hi(0, "NeoTreeGitRenamed", { fg = "#f0740a" })
  hi(0, "NeoTreeGitStaged", { fg = "#21b386" })
  hi(0, "NeoTreeGitUnstaged", { fg = "#e69400" })
  hi(0, "NeoTreeGitUntracked", { fg = "#e69400" })
  hi(0, "NeoTreeIndentMarker", { fg = "#b5b9bd" })
  hi(0, "NeoTreeNormal", { bg = "#f0f0f1", fg = "#737474" })
  hi(0, "NeoTreeNormalNC", { bg = "#f0f0f1", fg = "#737474" })
  hi(0, "NeoTreeRootName", { bold = true, fg = "#424446" })
  hi(0, "NeoTreeSymbolicLinkTarget", { fg = "#21b386" })
  hi(0, "NeoTreeTabActive", { bg = "#f0f0f1", bold = true, fg = "#424446" })
  hi(0, "NeoTreeTabInactive", { bg = "#e1e2e4", fg = "#aeb3b6" })
  hi(0, "NeoTreeTabSeparatorActive", { bg = "#f0f0f1", fg = "#f0f0f1" })
  hi(0, "NeoTreeTabSeparatorInactive", { bg = "#e1e2e4", fg = "#e1e2e4" })
  hi(0, "NeoTreeTitleBar", { bg = "#f0f0f1", bold = true, fg = "#671ff0" })
  hi(0, "NeoTreeVertSplit", { bg = "#f7f8f8", fg = "#e8e9ea" })
  hi(0, "NeoTreeWinSeparator", { bg = "#f7f8f8", bold = true, fg = "#e8e9ea" })
  hi(0, "NonText", { fg = "#b5b9bd" })
  hi(0, "Normal", { bg = "#f7f8f8", fg = "#4f4f4f" })
  hi(0, "NormalFloat", { bg = "#e1e2e3", fg = "#737474" })
  hi(0, "NormalNC", { bg = "#eaebeb", fg = "#4f4f4f" })
  hi(0, "NotifyBackground", { bg = "#f7f8f8", fg = "#737474" })
  hi(0, "NotifyDEBUGBody", { bg = "#f0f0f1", fg = "#737474" })
  hi(0, "NotifyDEBUGBorder", { bg = "#f0f0f1", fg = "#21b386" })
  hi(0, "NotifyDEBUGIcon", { bg = "#f0f0f1", fg = "#21b386" })
  hi(0, "NotifyDEBUGTitle", { bg = "#f0f0f1", fg = "#21b386" })
  hi(0, "NotifyERRORBody", { bg = "#f0f0f1", fg = "#737474" })
  hi(0, "NotifyERRORBorder", { bg = "#f0f0f1", fg = "#e72f1f" })
  hi(0, "NotifyERRORIcon", { bg = "#f0f0f1", fg = "#e72f1f" })
  hi(0, "NotifyERRORTitle", { bg = "#f0f0f1", fg = "#e72f1f" })
  hi(0, "NotifyINFOBody", { bg = "#f0f0f1", fg = "#737474" })
  hi(0, "NotifyINFOBorder", { bg = "#f0f0f1", fg = "#42ad17" })
  hi(0, "NotifyINFOIcon", { bg = "#f0f0f1", fg = "#42ad17" })
  hi(0, "NotifyINFOTitle", { bg = "#f0f0f1", fg = "#42ad17" })
  hi(0, "NotifyLogTime", { bg = "#f0f0f1", fg = "#aeb3b6" })
  hi(0, "NotifyLogTitle", { bg = "#f0f0f1", fg = "#3f8cea" })
  hi(0, "NotifyTRACEBody", { bg = "#f0f0f1", fg = "#737474" })
  hi(0, "NotifyTRACEIcon", { bg = "#f0f0f1", fg = "#671ff0" })
  hi(0, "NotifyTRACERBorder", { bg = "#f0f0f1", fg = "#671ff0" })
  hi(0, "NotifyTRACETitle", { bg = "#f0f0f1", fg = "#671ff0" })
  hi(0, "NotifyWARNBody", { bg = "#f0f0f1", fg = "#737474" })
  hi(0, "NotifyWARNBorder", { bg = "#f0f0f1", fg = "#f0740a" })
  hi(0, "NotifyWARNIcon", { bg = "#f0f0f1", fg = "#f0740a" })
  hi(0, "NotifyWARNTitle", { bg = "#f0f0f1", fg = "#f0740a" })
  hi(0, "Number", { fg = "#a34500" })
  hi(0, "Operator", { fg = "#4f4f4f" })
  hi(0, "Pmenu", { bg = "#e1e2e3", fg = "#737474" })
  hi(0, "PmenuSbar", { bg = "#e1e2e3" })
  hi(0, "PmenuSel", { bg = "#e7e9eb", blend = 0, bold = true })
  hi(0, "PmenuThumb", { bg = "#671ff0", blend = 0 })
  hi(0, "PreCondit", { fg = "#00508a" })
  hi(0, "PreProc", { fg = "#7300b8" })
  hi(0, "Question", { fg = "#671ff0" })
  hi(0, "QuickFixLine", { bg = "#e69400", fg = "#f7f8f8" })
  hi(0, "Repeat", { fg = "#9e007c" })
  hi(0, "Search", { bg = "#e7e9eb" })
  hi(0, "SignColumn", {})
  hi(0, "Special", { fg = "#00508a" })
  hi(0, "SpecialChar", { fg = "#00508a" })
  hi(0, "SpecialComment", { fg = "#b5b9bd" })
  hi(0, "SpecialKey", { fg = "#737474" })
  hi(0, "SpellBad", { sp = "#e72f1f", undercurl = true })
  hi(0, "SpellCap", { sp = "#e69400", undercurl = true })
  hi(0, "SpellLocal", { sp = "#3f8cea", undercurl = true })
  hi(0, "SpellRare", { sp = "#42ad17", undercurl = true })
  hi(0, "Statement", { fg = "#9e007c" })
  hi(0, "StatusCommand", { bg = "#e69400", fg = "#e1e2e4" })
  hi(0, "StatusInactive", { bg = "#aeb3b6", fg = "#e1e2e4" })
  hi(0, "StatusInsert", { bg = "#42ad17", fg = "#e1e2e4" })
  hi(0, "StatusLine", { bg = "#e1e2e4", fg = "#737474" })
  hi(0, "StatusLineNC", { fg = "#aeb3b6" })
  hi(0, "StatusNormal", { bg = "#3f8cea", fg = "#e1e2e4" })
  hi(0, "StatusReplace", { bg = "#e72f1f", fg = "#e1e2e4" })
  hi(0, "StatusTerminal", { link = "StatusInsert" })
  hi(0, "StatusVisual", { bg = "#671ff0", fg = "#e1e2e4" })
  hi(0, "StorageClass", { fg = "#00508a" })
  hi(0, "String", { fg = "#345e00" })
  hi(0, "Structure", { fg = "#7300b8" })
  hi(0, "Substitute", { bg = "#e72f1f", bold = true, fg = "#f7f8f8" })
  hi(0, "TabLine", { bg = "#e1e2e4", fg = "#aeb3b6" })
  hi(0, "TabLineFill", { bg = "#e1e2e4" })
  hi(0, "TabLineSel", { bg = "#f7f8f8", bold = true, fg = "#424446", italic = true })
  hi(0, "Tag", { fg = "#00508a" })
  hi(0, "TelescopeBorder", { bg = "#e1e2e3", fg = "#e7e9eb" })
  hi(0, "TelescopeMatching", { bold = true, fg = "#17191c" })
  hi(0, "TelescopeMultiIcon", { fg = "#3f8cea" })
  hi(0, "TelescopeMultiSelection", { fg = "#00508a" })
  hi(0, "TelescopeNormal", { bg = "#e1e2e3" })
  hi(0, "TelescopePreviewBorder", { bg = "#e1e2e3", fg = "#e1e2e3" })
  hi(0, "TelescopePreviewNormal", { bg = "#e1e2e3" })
  hi(0, "TelescopePreviewTitle", { bg = "#345e00", fg = "#e1e2e3" })
  hi(0, "TelescopePromptBorder", { bg = "#e7e9eb", fg = "#e7e9eb" })
  hi(0, "TelescopePromptNormal", { bg = "#e7e9eb", fg = "#737474" })
  hi(0, "TelescopePromptPrefix", { bg = "#e7e9eb", fg = "#e72f1f" })
  hi(0, "TelescopePromptTitle", { bg = "#e72f1f", fg = "#e1e2e3" })
  hi(0, "TelescopeResultsBorder", { bg = "#e1e2e3", fg = "#e1e2e3" })
  hi(0, "TelescopeResultsNormal", { bg = "#e1e2e3" })
  hi(0, "TelescopeResultsTitle", { bg = "#e1e2e3", fg = "#e1e2e3" })
  hi(0, "TelescopeSelection", { link = "PmenuSel" })
  hi(0, "TelescopeSelectionCaret", { fg = "#671ff0" })
  hi(0, "Terminal", { bg = "#f7f8f8", fg = "#737474" })
  hi(0, "Title", { bg = "#f0f0f1", bold = true, fg = "#671ff0" })
  hi(0, "Todo", { fg = "#e69400" })
  hi(0, "Type", { fg = "#00508a" })
  hi(0, "Typedef", { fg = "#7300b8" })
  hi(0, "Underlined", { fg = "#00615b", underline = true })
  hi(0, "VertSplit", { bg = "#f7f8f8", fg = "#e8e9ea" })
  hi(0, "Visual", { bg = "#e7e9eb" })
  hi(0, "VisualNOS", { fg = "#e7e9eb" })
  hi(0, "WarningMsg", { fg = "#e69400" })
  hi(0, "WhichKey", { fg = "#21b386" })
  hi(0, "WhichKeyBorder", { link = "FloatBorder" })
  hi(0, "WhichKeyDesc", { fg = "#671ff0" })
  hi(0, "WhichKeyFloat", { link = "NormalFloat" })
  hi(0, "WhichKeyGroup", { fg = "#3f8cea" })
  hi(0, "WhichKeySeparator", { fg = "#b5b9bd" })
  hi(0, "WhichKeyValue", { fg = "#424446" })
  hi(0, "WildMenu", { bg = "#671ff0", fg = "#f7f8f8" })
  hi(0, "WinBar", { fg = "#999fa3" })
  hi(0, "WinBarNC", { bg = "#eaebeb", fg = "#aeb3b6" })
  hi(0, "WinSeparator", { bg = "#f7f8f8", fg = "#e8e9ea" })
  hi(0, "WindowPickerStatusLine", { fg = "#e72f1f" })
  hi(0, "WindowPickerStatusLineNC", { fg = "#e72f1f" })
  hi(0, "WindowPickerWinBar", { fg = "#e72f1f" })
  hi(0, "WindowPickerWinBarNC", { fg = "#e72f1f" })
  hi(0, "lCursor", { link = "Cursor" })

  -- Terminal colors
  local g = vim.g

  g.terminal_color_0 = "#e1e2e4"
  g.terminal_color_1 = "#990000"
  g.terminal_color_2 = "#345e00"
  g.terminal_color_3 = "#7300b8"
  g.terminal_color_4 = "#00508a"
  g.terminal_color_5 = "#9e007c"
  g.terminal_color_6 = "#00615b"
  g.terminal_color_7 = "#737474"
  g.terminal_color_8 = "#b9babc"
  g.terminal_color_9 = "#c12828"
  g.terminal_color_10 = "#5c8628"
  g.terminal_color_11 = "#9b28e0"
  g.terminal_color_12 = "#2878b2"
  g.terminal_color_13 = "#c628a4"
  g.terminal_color_14 = "#288983"
  g.terminal_color_15 = "#595959"
end
