---@meta _
---This file is @generated by update_types.sh. Do not modify it directly.
-- stylua: ignore start

---@class meowim.plugins
local meowim_plugins = {}
meowim_plugins["blink-cmp"] = require("meowim.plugins.blink-cmp")
meowim_plugins["conform"] = require("meowim.plugins.conform")
meowim_plugins["git-conflict"] = require("meowim.plugins.git-conflict")
meowim_plugins["guess-indent"] = require("meowim.plugins.guess-indent")
meowim_plugins["lazydev"] = require("meowim.plugins.lazydev")
meowim_plugins["meoline"] = require("meowim.plugins.meoline")
meowim_plugins["nvim-lint"] = require("meowim.plugins.nvim-lint")
meowim_plugins["nvim-lspconfig"] = require("meowim.plugins.nvim-lspconfig")
meowim_plugins["nvim-treesitter"] = require("meowim.plugins.nvim-treesitter")
meowim_plugins["nvim-treesitter-textobjects"] = require("meowim.plugins.nvim-treesitter-textobjects")
meowim_plugins["quicker"] = require("meowim.plugins.quicker")
meowim_plugins["scope"] = require("meowim.plugins.scope")
meowim_plugins["smart-splits"] = require("meowim.plugins.smart-splits")
meowim_plugins["snacks"] = require("meowim.plugins.snacks")

---@class meowim.plugins.mini
local meowim_plugins_mini = {}
meowim_plugins_mini["ai"] = require("meowim.plugins.mini.ai")
meowim_plugins_mini["align"] = require("meowim.plugins.mini.align")
meowim_plugins_mini["base16"] = require("meowim.plugins.mini.base16")
meowim_plugins_mini["basics"] = require("meowim.plugins.mini.basics")
meowim_plugins_mini["bracketed"] = require("meowim.plugins.mini.bracketed")
meowim_plugins_mini["bufremove"] = require("meowim.plugins.mini.bufremove")
meowim_plugins_mini["clue"] = require("meowim.plugins.mini.clue")
meowim_plugins_mini["comment"] = require("meowim.plugins.mini.comment")
meowim_plugins_mini["diff"] = require("meowim.plugins.mini.diff")
meowim_plugins_mini["extra"] = require("meowim.plugins.mini.extra")
meowim_plugins_mini["files"] = require("meowim.plugins.mini.files")
meowim_plugins_mini["git"] = require("meowim.plugins.mini.git")
meowim_plugins_mini["hipatterns"] = require("meowim.plugins.mini.hipatterns")
meowim_plugins_mini["icons"] = require("meowim.plugins.mini.icons")
meowim_plugins_mini["indentscope"] = require("meowim.plugins.mini.indentscope")
meowim_plugins_mini["keymap"] = require("meowim.plugins.mini.keymap")
meowim_plugins_mini["misc"] = require("meowim.plugins.mini.misc")
meowim_plugins_mini["notify"] = require("meowim.plugins.mini.notify")
meowim_plugins_mini["operators"] = require("meowim.plugins.mini.operators")
meowim_plugins_mini["pairs"] = require("meowim.plugins.mini.pairs")
meowim_plugins_mini["pick"] = require("meowim.plugins.mini.pick")
meowim_plugins_mini["sessions"] = require("meowim.plugins.mini.sessions")
meowim_plugins_mini["snippets"] = require("meowim.plugins.mini.snippets")
meowim_plugins_mini["starter"] = require("meowim.plugins.mini.starter")
meowim_plugins_mini["surround"] = require("meowim.plugins.mini.surround")
